= PythonTeX Trial
motchy <motchy869@gmail.com>
:reproducible:
:revnumber: 0.1.0
:revdate: 2024-11-11
:description: My PythonTeX Trial
:stem: latexmath
:sectanchors:
:sectnums:
:source-highlighter: highlightjs
:highlightjs-theme: github-dark

== Definitions

* workspace directory: the directory where this README.md file is located.
* build output directory: `<workspace directory>/build-out`. The output PDF file is generated here.

== How to Build this document

=== Method 1: Using Command Line

1. Open a terminal and navigate to the workspace directory.
2. Run the following command to compile the document:
+
[source, bash]
----
bash -c 'cd src; lualatex -file-line-error -synctex=1 -interaction=nonstopmode -halt-on-error -output-directory=../build-out pythontex_trial.tex; pythontex ../build-out/pythontex_trial; lualatex -file-line-error -synctex=1 -interaction=nonstopmode -halt-on-error -output-directory=../build-out pythontex_trial.tex'
----

=== Method 2: (recommended) Using VS Code and LaTeX Workshop

We need to install link:https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop[LaTeX Workshop].

. Open the workspace directory in VS Code.
. Open the command palette (Ctrl+Shift+P) and type "LaTeX Workshop: Build with recipe".
. Select "lualatex->pythontex->lualatex". +
Don't worry. `./vscode/settings.json` is already configured appropriately. It is recommended to look at the settings and you will learn how this works.

. Wait for the build to finish.
